-- Safe division function
DROP FUNCTION IF EXISTS SafeDiv;

DELIMITER $$

CREATE FUNCTION SafeDiv(
    a INT,
    b INT)
    RETURNS FLOAT
    DETERMINISTIC
RETURN IFNULL((a * 1.0) / NULLIF(b, 0), 0);
